<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * BankAccountConnectionMeta
 */
namespace OpenAPI\Server\Model;

/**
 * BankAccountConnectionMeta
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class BankAccountConnectionMeta
{
    /**
    *
    * The unique identifier for a resource.
    * @param string $id
    *
    * The Workspace ID in which the verification has been created.
    * @param string $workspaceId
    *
    * Creation date of the Bank Account Connection Verification.
    * @param \DateTime $createdAt
    *
    * Update date of the Bank Account Connection Verification.
    * @param \DateTime $updatedAt
    *
    * 
    * @param \OpenAPI\Server\Model\BankAccountConnectionStatus $status
    *
    * List of status codes. Indicates the cause when the status is pending, verified, failed or inconclusive.
    * @param string[] $statusCodes
    *
    * Indicates if the personal data extracted from the Bank Account Connection has been anonymized. If set to &#x60;true&#x60;, the personal data has been anonymized and most fields will be NULL.
    * @param bool $dataAnonymized
    */

    public function __construct(
        public string $id,
        public string $workspaceId,
        public \DateTime $createdAt,
        public \DateTime $updatedAt,
        public \OpenAPI\Server\Model\BankAccountConnectionStatus $status,
        public array $statusCodes,
        public bool $dataAnonymized,
    ) {}
}

