<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CompanyFullAllOfDataLegalRepresentatives
 */
namespace OpenAPI\Server\Model;

/**
 * CompanyFullAllOfDataLegalRepresentatives
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CompanyFullAllOfDataLegalRepresentatives
{
    /**
    *
    * The representative&#39;s role within the company.
    * @param null | string $title
    *
    * 
    * @param null | \OpenAPI\Server\Model\CompanyFullAllOfDataLegalRepresentativesType $type
    *
    * The representative&#39;s first name in case of a natural person, otherwise null.
    * @param null | string $firstName
    *
    * The representative&#39;s last name in case of a natural person, otherwise null.
    * @param null | string $lastName
    *
    * The representative&#39;s birthdate in case of a natural person, otherwise null.
    * @param null | \DateTime $bornOn
    *
    * The representative&#39;s company name in case of a legal person, otherwise null.
    * @param null | string $companyName
    *
    * The representative&#39;s company number in case of a legal person, otherwise null.
    * @param null | string $companyNumber
    */

    public function __construct(
        public ?string $title = null,
        public ?\OpenAPI\Server\Model\CompanyFullAllOfDataLegalRepresentativesType $type = null,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?\DateTime $bornOn = null,
        public ?string $companyName = null,
        public ?string $companyNumber = null,
    ) {}
}

