<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CreateField
 */
namespace OpenAPI\Server\Model;

/**
 * CreateField
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CreateField
{
    /**
    *
    * 
    * @param string $signerId
    *
    * 
    * @param \OpenAPI\Server\Model\FieldReadOnlyTextType $type
    *
    * 
    * @param int $page
    *
    * 
    * @param int $x
    *
    * 
    * @param int $y
    *
    * The height must be calculated using the formula: \&quot;height &#x3D; number_of_lines \\* font_size \\* line_height\&quot;, where the line height is always set to 1.5.
    * @param null | int $height
    *
    * If not set, the width is automatically calculated with the read only text length.
    * @param null | int $width
    *
    * Provide extra context to explain why the Document is being signed. Once the Document is signed, the custom reason is stored in the Audit Trail and is included in the signature certificate. The default value is: \&quot;Signed by [Signer first name] [Signer last name]\&quot;.
    * @param null | string $reason
    *
    * Content of the Mention. You can use dynamic tags when creating the Mention: • &#x60;%date%&#x60; will display the current date when the Signer sign the Signature Request (eg. \&quot;24-03-2025\&quot;) • &#x60;%datetime%&#x60; will display the current date and time when the Signer signs the Signature Request (eg. \&quot;24-03-2025 10:30 UTC+0\&quot;)
    * @param string $mention
    *
    * 
    * @param null | \OpenAPI\Server\Model\CreateFieldFont $font
    *
    * Radio group&#39;s name
    * @param null | string $name
    *
    * 
    * @param int $maxLength
    *
    * If you don&#39;t want any question, you can give an empty string.
    * @param string $question
    *
    * 
    * @param null | string $instruction
    *
    * 
    * @param bool $optional
    *
    * If a default value is provided, the Field will be pre-filled with this value. The Signer can modify it before signing unless the Field is set to &#x60;read-only&#x60;.
    * @param null | string $defaultValue
    *
    * If set to &#x60;true&#x60;, the radio button cannot be modified by the Signer.
    * @param bool $readOnly
    *
    * 
    * @param int $size
    *
    * 
    * @param bool $checked
    *
    * 
    * @param \OpenAPI\Server\Model\RadioGroupRadiosInner[] $radios
    *
    * 
    * @param string $text
    */

    public function __construct(
        public string $signerId,
        public \OpenAPI\Server\Model\FieldReadOnlyTextType $type,
        public int $page,
        public int $x,
        public int $y,
        public string $mention,
        public int $maxLength,
        public string $question,
        public bool $optional = false,
        public bool $readOnly = false,
        public int $size = 24,
        public bool $checked = false,
        public array $radios,
        public string $text,
        public ?int $height = null,
        public ?int $width = null,
        public ?string $reason = null,
        public ?\OpenAPI\Server\Model\CreateFieldFont $font = null,
        public ?string $name = null,
        public ?string $instruction = null,
        public ?string $defaultValue = null,
    ) {}
}

