<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CreateCustomExperience
 */
namespace OpenAPI\Server\Model;

/**
 * CreateCustomExperience
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CreateCustomExperience
{
    /**
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $name
    *
    * 
    * @param null | bool $landingPageDisabled
    *
    * 
    * @param null | bool $sidePanelDisabled
    *
    * Hexadecimal color value
    * @param null | string $backgroundColor
    *
    * Hexadecimal color value
    * @param null | string $buttonColor
    *
    * Hexadecimal color value
    * @param null | string $textColor
    *
    * Hexadecimal color value
    * @param null | string $textButtonColor
    *
    * 
    * @param null | \OpenAPI\Server\Model\CustomExperienceDisabledNotificationsType[] $disabledNotifications
    *
    * 
    * @param null | bool $emailLogoDisabled
    *
    * 
    * @param null | bool $emailHeaderTextDisabled
    *
    * 
    * @param null | bool $emailFooterSignatureDisabled
    *
    * 
    * @param null | bool $emailExpirationTextDisabled
    *
    * 
    * @param null | bool $recipientsActivityDisabled
    *
    * If false, signers won&#39;t be able to download documents before signing.
    * @param null | bool $downloadDocumentsDisabled
    *
    * 
    * @param null | \OpenAPI\Server\Model\CreateCustomExperienceRedirectUrls $redirectUrls
    *
    * 
    * @param \OpenAPI\Server\Model\LogoLayout $logoLayout
    */

    public function __construct(
        public string $name,
        public \OpenAPI\Server\Model\LogoLayout $logoLayout,
        public ?bool $landingPageDisabled = false,
        public ?bool $sidePanelDisabled = false,
        public ?string $backgroundColor = null,
        public ?string $buttonColor = null,
        public ?string $textColor = null,
        public ?string $textButtonColor = null,
        public ?array $disabledNotifications = null,
        public ?bool $emailLogoDisabled = false,
        public ?bool $emailHeaderTextDisabled = false,
        public ?bool $emailFooterSignatureDisabled = false,
        public ?bool $emailExpirationTextDisabled = false,
        public ?bool $recipientsActivityDisabled = true,
        public ?bool $downloadDocumentsDisabled = false,
        public ?\OpenAPI\Server\Model\CreateCustomExperienceRedirectUrls $redirectUrls = null,
    ) {}
}

