<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CreateElectronicSealPayload
 */
namespace OpenAPI\Server\Model;

/**
 * CreateElectronicSealPayload
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CreateElectronicSealPayload
{
    /**
    *
    * Specify which Electronic Seal Document to use for creating an Electronic Seal.
    * @param string $documentId
    *
    * Specify which Electronic Seal Image to use for creating an Electronic Seal.
    * @param null | string $imageId
    *
    * Store a custom id that will be added to webhooks
    * @param null | string $externalId
    *
    * Fields you want to add to your Document. At least one Seal Field is mandatory.
    * @param \OpenAPI\Server\Model\CreateElectronicSealPayloadFieldsInner[] $fields
    *
    * 
    * @param null | \OpenAPI\Server\Model\CreateElectronicSealPayloadSignatureLevel $signatureLevel
    *
    * Specify which certificate to use for creating an Electronic Seal (only available for advanced_electronic_signature level).
    * @param null | string $certificateId
    */

    public function __construct(
        public string $documentId,
        public array $fields,
        public ?string $imageId = null,
        public ?string $externalId = null,
        public ?\OpenAPI\Server\Model\CreateElectronicSealPayloadSignatureLevel $signatureLevel = null,
        public ?string $certificateId = null,
    ) {}
}

