<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CreateContact
 */
namespace OpenAPI\Server\Model;

/**
 * CreateContact
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CreateContact
{
    /**
    *
    * 
    * @param string $firstName
    *
    * 
    * @param string $lastName
    *
    * 
    * @param string $email
    *
    * 
    * @param \OpenAPI\Server\Model\Locale $locale
    *
    * E.164 format
    * @param string $phoneNumber
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $companyName
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $jobTitle
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $addressLine1
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $addressLine2
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $addressCity
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $addressPostalCode
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param string $addressCountry
    *
    * 
    * @param null | string $workspaceId
    */

    public function __construct(
        public string $firstName,
        public string $lastName,
        public string $email,
        public \OpenAPI\Server\Model\Locale $locale,
        public string $phoneNumber,
        public string $companyName,
        public string $jobTitle,
        public string $addressLine1,
        public string $addressLine2,
        public string $addressCity,
        public string $addressPostalCode,
        public string $addressCountry,
        public ?string $workspaceId = null,
    ) {}
}

