<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CreateUser
 */
namespace OpenAPI\Server\Model;

/**
 * CreateUser
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class CreateUser
{
    /**
    *
    * The email address must not match any existing User&#39;s email.
    * @param string $email
    *
    * 
    * @param \OpenAPI\Server\Model\UserSRole $role
    *
    * 
    * @param \OpenAPI\Server\Model\Locale $locale
    *
    * The new User must be associated with at least one Workspace in the Organization.
    * @param string[] $workspaces
    *
    * User&#39;s first name
    * @param null | string $firstName
    *
    * User&#39;s last name
    * @param null | string $lastName
    *
    * E.164 format
    * @param null | string $phoneNumber
    *
    * This property cannot start or end with whitespace, does not allow HTML tags, URL or email.
    * @param null | string $jobTitle
    */

    public function __construct(
        public string $email,
        public \OpenAPI\Server\Model\UserSRole $role,
        public \OpenAPI\Server\Model\Locale $locale,
        public array $workspaces,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?string $phoneNumber = null,
        public ?string $jobTitle = null,
    ) {}
}

