<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * CustomExperienceDisabledNotificationsType
 */
namespace OpenAPI\Server\Model;

/**
 * CustomExperienceDisabledNotificationsType
 */
enum CustomExperienceDisabledNotificationsType: string
{
        case APPROVER_EXPIRATION_DATE_REMINDER = 'approver.expiration_date_reminder';
        case APPROVER_CANCELED = 'approver.canceled';
        case APPROVER_EXPIRATION_DATE_UPDATED = 'approver.expiration_date_updated';
        case FOLLOWER_APPROVED = 'follower.approved';
        case FOLLOWER_CANCELED = 'follower.canceled';
        case FOLLOWER_COMPLETED = 'follower.completed';
        case FOLLOWER_EXPIRED = 'follower.expired';
        case FOLLOWER_REJECTED = 'follower.rejected';
        case FOLLOWER_ACTIVATED = 'follower.activated';
        case FOLLOWER_SIGNED = 'follower.signed';
        case SENDER_APPROVED = 'sender.approved';
        case SENDER_CANCELED = 'sender.canceled';
        case SENDER_COMPLETED = 'sender.completed';
        case SENDER_REJECTED = 'sender.rejected';
        case SENDER_SIGNED = 'sender.signed';
        case SIGNER_EXPIRATION_DATE_REMINDER = 'signer.expiration_date_reminder';
        case SIGNER_CANCELED = 'signer.canceled';
        case SIGNER_COMPLETED = 'signer.completed';
        case SIGNER_SIGNED = 'signer.signed';
        case SIGNER_EXPIRATION_DATE_UPDATED = 'signer.expiration_date_updated';
        case SIGNER_SIGNATURE_REQUESTED = 'signer.signature_requested';
}
