<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * DisabledEmailNotificationInner
 */
namespace OpenAPI\Server\Model;

/**
 * DisabledEmailNotificationInner
 * @description If the delivery mode is \"email\" for the Signer, you can list all the emails you don't want them to receive.
 */
enum DisabledEmailNotificationInner: string
{
        case SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_NOT_SIGNED = 'signer.signature_request_canceled_due_to_an_error.signer_who_has_not_signed';
        case SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_ALREADY_SIGNED = 'signer.signature_request_canceled_due_to_an_error.signer_who_has_already_signed';
        case SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_NOT_SIGNED = 'signer.signature_request_canceled_by_sender.signer_who_has_not_signed';
        case SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_ALREADY_SIGNED = 'signer.signature_request_canceled_by_sender.signer_who_has_already_signed';
        case SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_ONE_SIGNER = 'signer.signature_request_done.signature_request_contains_one_signer';
        case SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_MULTIPLE_SIGNERS = 'signer.signature_request_done.signature_request_contains_multiple_signers';
        case SIGNER_SIGNATURE_REQUEST_WITH_MULTIPLE_SIGNERS_SIGNED_SIGNED_BY_A_SIGNER = 'signer.signature_request_with_multiple_signers_signed.signed_by_a_signer';
        case SIGNER_SIGNATURE_REQUEST_UPDATED_NEW_EXPIRATION_DATE = 'signer.signature_request_updated.new_expiration_date';
        case SIGNER_SIGNATURE_REQUEST_UPDATED_BY_SENDER_NEW_SIGNER_DETAILS = 'signer.signature_request_updated_by_sender.new_signer_details';
        case SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_FIRST_NOTIFICATION = 'signer.signature_request_signature_requested.first_notification';
        case SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_REMINDER_TO_SIGN = 'signer.signature_request_signature_requested.reminder_to_sign';
}
