<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * ElectronicSealAuditTrail
 */
namespace OpenAPI\Server\Model;

/**
 * ElectronicSealAuditTrail
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class ElectronicSealAuditTrail
{
    /**
    *
    * 
    * @param float $version
    *
    * 
    * @param string $classification
    *
    * 
    * @param object $organization
    *
    * 
    * @param object $seal
    *
    * 
    * @param object $document
    */

    public function __construct(
        public float $version,
        public string $classification,
        public object $organization,
        public object $seal,
        public object $document,
    ) {}
}

