<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * FieldsInput
 */
namespace OpenAPI\Server\Model;

/**
 * FieldsInput
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class FieldsInput
{
    /**
    *
    * 
    * @param string $documentId
    *
    * 
    * @param \OpenAPI\Server\Model\FieldRadioButtonGroupType $type
    *
    * 
    * @param int $page
    *
    * 
    * @param int $x
    *
    * 
    * @param int $y
    *
    * The height must be 24 or a multiple of 15 greater than 24.
    * @param int $height
    *
    * If not set, the width is automatically calculated with the max_length value
    * @param int $width
    *
    * Provide extra context to explain why the Document is being signed. Once the Document is signed, the custom reason is stored in the Audit Trail and is included in the signature certificate. The default value is: \&quot;Signed by [Signer first name] [Signer last name]\&quot;.
    * @param null | string $reason
    *
    * 
    * @param string $mention
    *
    * Radio group&#39;s name
    * @param null | string $name
    *
    * 
    * @param int $maxLength
    *
    * 
    * @param string $question
    *
    * 
    * @param null | string $instruction
    *
    * 
    * @param bool $optional
    *
    * If a default value is provided, the Field will be pre-filled with this value. The Signer can modify it before signing unless the Field is set to &#x60;read-only&#x60;.
    * @param null | string $defaultValue
    *
    * If set to &#x60;true&#x60;, the radio button cannot be modified by the Signer.
    * @param bool $readOnly
    *
    * The omission of size parameter is considered as deprecated. The size determines both the width and height of the checkbox.
    * @param int $size
    *
    * 
    * @param bool $checked
    *
    * 
    * @param bool $defaultChecked
    *
    * 
    * @param \OpenAPI\Server\Model\RadioGroup2RadiosInner[] $radios
    */

    public function __construct(
        public string $documentId,
        public \OpenAPI\Server\Model\FieldRadioButtonGroupType $type,
        public int $page,
        public int $x,
        public int $y,
        public int $height,
        public int $width,
        public string $mention,
        public int $maxLength,
        public string $question,
        public bool $optional,
        public bool $readOnly = false,
        public int $size,
        public bool $checked,
        public bool $defaultChecked,
        public array $radios,
        public ?string $reason = null,
        public ?string $name = null,
        public ?string $instruction = null,
        public ?string $defaultValue = null,
    ) {}
}

