<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * IdentityDocumentFullAllOfDataExtractedFromDocument
 */
namespace OpenAPI\Server\Model;

/**
 * IdentityDocumentFullAllOfDataExtractedFromDocument
 * @description Information extracted from the verified identity document
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class IdentityDocumentFullAllOfDataExtractedFromDocument
{
    /**
    *
    * The document holder&#39;s first name as it appears on the identity document
    * @param null | string $firstName
    *
    * The document holder&#39;s birth name (family name at birth)
    * @param null | string $birthName
    *
    * The document holder&#39;s current last name (may differ from birth name)
    * @param null | string $lastName
    *
    * The document holder&#39;s date of birth as it appears on the document
    * @param null | \DateTime $bornOn
    *
    * The holder&#39;s place of birth as it appears on the document
    * @param null | string $birthLocation
    *
    * 
    * @param null | \OpenAPI\Server\Model\IdentityDocumentFullAllOfDataExtractedFromDocumentGender $gender
    *
    * The holder&#39;s complete postal address as it appears on the document
    * @param null | string $fullAddress
    *
    * 
    * @param null | \OpenAPI\Server\Model\IdentityDocumentFullAllOfDataExtractedFromDocumentType $type
    *
    * The country that issued the document (ISO 3166-1 alpha-2 code)
    * @param null | string $issuingCountryCode
    *
    * The date when the document was issued
    * @param null | \DateTime $issuedOn
    *
    * The date when the document legally expires
    * @param null | \DateTime $expiredOn
    *
    * Document identifier number (may contain letters)
    * @param null | string $documentNumber
    *
    * 
    * @param \OpenAPI\Server\Model\GetIdDocumentVerification200ResponseAllOfExtractedFromDocumentMrz $mrz
    */

    public function __construct(
        public \OpenAPI\Server\Model\GetIdDocumentVerification200ResponseAllOfExtractedFromDocumentMrz $mrz,
        public ?string $firstName = null,
        public ?string $birthName = null,
        public ?string $lastName = null,
        public ?\DateTime $bornOn = null,
        public ?string $birthLocation = null,
        public ?\OpenAPI\Server\Model\IdentityDocumentFullAllOfDataExtractedFromDocumentGender $gender = null,
        public ?string $fullAddress = null,
        public ?\OpenAPI\Server\Model\IdentityDocumentFullAllOfDataExtractedFromDocumentType $type = null,
        public ?string $issuingCountryCode = null,
        public ?\DateTime $issuedOn = null,
        public ?\DateTime $expiredOn = null,
        public ?string $documentNumber = null,
    ) {}
}

