<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * InitiateIdentityVideo
 */
namespace OpenAPI\Server\Model;

/**
 * InitiateIdentityVideo
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class InitiateIdentityVideo
{
    /**
    *
    * The first name provided must match exactly as it appears on the ID document, as a consistency check will be performed. If multiple given names are listed on the document, you must provide only one of them.
    * @param string $firstName
    *
    * The last name provided must match exactly as it appears on the ID document, as a consistency check will be performed. If both a birth name and a usage name are listed on the document, you must provide one of them, but not both.
    * @param string $lastName
    *
    * The URL to redirect the person back to your application or website after the identity verification flow is complete.
    * @param string $redirectionUrl
    *
    * Enable face recognition step in the identity verification flow.
    * @param bool $faceRecognition
    *
    * Scopes the verification to a specific workspace. Defaults to the default workspace if not specified.
    * @param null | string $workspaceId
    */

    public function __construct(
        public string $firstName,
        public string $lastName,
        public string $redirectionUrl,
        public bool $faceRecognition = false,
        public ?string $workspaceId = null,
    ) {}
}

