<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * InitiateBankAccountWithNaturalPersonNaturalPerson
 */
namespace OpenAPI\Server\Model;

/**
 * InitiateBankAccountWithNaturalPersonNaturalPerson
 * @description The field can not be submitted if field \"legal_person\" is provided.
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class InitiateBankAccountWithNaturalPersonNaturalPerson
{
    /**
    *
    * Please provide the holder first name, exactly as it appears on the bank account document. Please match it exactly, with the same characters, same case. One exception: if the document mentions an honorary title, please don&#39;t provide it as part of the name.
    * @param string $firstName
    *
    * Please provide the holder last name, exactly as it appears on the bank account document. Please match it exactly, with the same characters, same case. One exception: if the document mentions an honorary title, please don&#39;t provide it as part of the name.
    * @param string $lastName
    */

    public function __construct(
        public string $firstName,
        public string $lastName,
    ) {}
}

