<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Mention2
 */
namespace OpenAPI\Server\Model;

/**
 * Mention2
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Mention2
{
    /**
    *
    * 
    * @param string $documentId
    *
    * 
    * @param \OpenAPI\Server\Model\FieldMentionType $type
    *
    * 
    * @param int $page
    *
    * 
    * @param int $x
    *
    * 
    * @param int $y
    *
    * If not set, the width is automatically calculated with the mention length
    * @param int $width
    *
    * The height must be 24 or a multiple of 15 greater than 24. If height is not provided, it will be calculated depending on the number of newlines in the mention
    * @param null | int $height
    *
    * 
    * @param string $mention
    *
    * Name of the Field.
    * @param null | string $name
    */

    public function __construct(
        public string $documentId,
        public \OpenAPI\Server\Model\FieldMentionType $type,
        public int $page,
        public int $x,
        public int $y,
        public int $width,
        public string $mention,
        public ?int $height = null,
        public ?string $name = null,
    ) {}
}

