<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SignatureRequestInListReminderSettingsIntervalInDays
 */
namespace OpenAPI\Server\Model;

/**
 * SignatureRequestInListReminderSettingsIntervalInDays
 */
enum SignatureRequestInListReminderSettingsIntervalInDays: int
{
        case NUMBER_1 = 1;
        case NUMBER_2 = 2;
        case NUMBER_7 = 7;
        case NUMBER_14 = 14;
}
