<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SignerSignatureLevel
 */
namespace OpenAPI\Server\Model;

/**
 * SignerSignatureLevel
 */
enum SignerSignatureLevel: string
{
        case ELECTRONIC_SIGNATURE = 'electronic_signature';
        case ADVANCED_ELECTRONIC_SIGNATURE = 'advanced_electronic_signature';
        case QUALIFIED_ELECTRONIC_SIGNATURE = 'qualified_electronic_signature';
}
