<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * SignatureRequestStatus
 */
namespace OpenAPI\Server\Model;

/**
 * SignatureRequestStatus
 */
enum SignatureRequestStatus: string
{
        case DRAFT = 'draft';
        case ONGOING = 'ongoing';
        case DONE = 'done';
        case DELETED = 'deleted';
        case EXPIRED = 'expired';
        case CANCELED = 'canceled';
        case APPROVAL = 'approval';
        case REJECTED = 'rejected';
        case DECLINED = 'declined';
}
