<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Text1
 */
namespace OpenAPI\Server\Model;

/**
 * Text1
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Text1
{
    /**
    *
    * 
    * @param string $signerId
    *
    * 
    * @param int $page
    *
    * 
    * @param int $x
    *
    * 
    * @param int $y
    *
    * If not set, the width is automatically calculated with the max_length value
    * @param int $width
    *
    * The height must be 24 or a multiple of 15 greater than 24.
    * @param int $height
    *
    * 
    * @param int $maxLength
    *
    * If you don&#39;t want any question, you can give an empty string.
    * @param string $question
    *
    * 
    * @param null | string $instruction
    *
    * 
    * @param bool $optional
    *
    * 
    * @param null | \OpenAPI\Server\Model\UpdateFieldFont $font
    *
    * Name of the Field.
    * @param null | string $name
    *
    * If a default value is provided, the Field will be pre-filled with this value. The Signer can modify it before signing unless the Field is set to &#x60;read-only&#x60;.
    * @param null | string $defaultValue
    *
    * If set to &#x60;true&#x60;, the Signer cannot modify the Field and the default value (if provided) will remain unchanged.
    * @param bool $readOnly
    */

    public function __construct(
        public string $signerId,
        public int $page,
        public int $x,
        public int $y,
        public int $width,
        public int $height,
        public int $maxLength,
        public string $question,
        public bool $optional = false,
        public bool $readOnly = false,
        public ?string $instruction = null,
        public ?\OpenAPI\Server\Model\UpdateFieldFont $font = null,
        public ?string $name = null,
        public ?string $defaultValue = null,
    ) {}
}

