<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * WatchlistFullAllOfDataPoliticallyExposedPersonPositions
 */
namespace OpenAPI\Server\Model;

/**
 * WatchlistFullAllOfDataPoliticallyExposedPersonPositions
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class WatchlistFullAllOfDataPoliticallyExposedPersonPositions
{
    /**
    *
    * Title of the political position
    * @param null | string $title
    *
    * Whether the person is currently politically exposed
    * @param bool $active
    *
    * ISO country code where the position is held
    * @param null | string $countryCode
    *
    * Date when the position started
    * @param null | string $startedOn
    *
    * Date when the position ended − null if ongoing
    * @param null | string $endedOn
    *
    * Sources of this information
    * @param \OpenAPI\Server\Model\WatchlistFullAllOfDataPoliticallyExposedPersonSources[] $sources
    */

    public function __construct(
        public bool $active,
        public array $sources,
        public ?string $title = null,
        public ?string $countryCode = null,
        public ?string $startedOn = null,
        public ?string $endedOn = null,
    ) {}
}

