<?php
/**
 * CustomExperienceDisabledNotificationsType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public Api v3
 *
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomExperienceDisabledNotificationsType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomExperienceDisabledNotificationsType
{
    /**
     * Possible values of this enum
     */
    public const APPROVER_EXPIRATION_DATE_REMINDER = 'approver.expiration_date_reminder';

    public const APPROVER_CANCELED = 'approver.canceled';

    public const APPROVER_EXPIRATION_DATE_UPDATED = 'approver.expiration_date_updated';

    public const FOLLOWER_APPROVED = 'follower.approved';

    public const FOLLOWER_CANCELED = 'follower.canceled';

    public const FOLLOWER_COMPLETED = 'follower.completed';

    public const FOLLOWER_EXPIRED = 'follower.expired';

    public const FOLLOWER_REJECTED = 'follower.rejected';

    public const FOLLOWER_ACTIVATED = 'follower.activated';

    public const FOLLOWER_SIGNED = 'follower.signed';

    public const SENDER_APPROVED = 'sender.approved';

    public const SENDER_CANCELED = 'sender.canceled';

    public const SENDER_COMPLETED = 'sender.completed';

    public const SENDER_REJECTED = 'sender.rejected';

    public const SENDER_SIGNED = 'sender.signed';

    public const SIGNER_EXPIRATION_DATE_REMINDER = 'signer.expiration_date_reminder';

    public const SIGNER_CANCELED = 'signer.canceled';

    public const SIGNER_COMPLETED = 'signer.completed';

    public const SIGNER_SIGNED = 'signer.signed';

    public const SIGNER_EXPIRATION_DATE_UPDATED = 'signer.expiration_date_updated';

    public const SIGNER_SIGNATURE_REQUESTED = 'signer.signature_requested';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPROVER_EXPIRATION_DATE_REMINDER,
            self::APPROVER_CANCELED,
            self::APPROVER_EXPIRATION_DATE_UPDATED,
            self::FOLLOWER_APPROVED,
            self::FOLLOWER_CANCELED,
            self::FOLLOWER_COMPLETED,
            self::FOLLOWER_EXPIRED,
            self::FOLLOWER_REJECTED,
            self::FOLLOWER_ACTIVATED,
            self::FOLLOWER_SIGNED,
            self::SENDER_APPROVED,
            self::SENDER_CANCELED,
            self::SENDER_COMPLETED,
            self::SENDER_REJECTED,
            self::SENDER_SIGNED,
            self::SIGNER_EXPIRATION_DATE_REMINDER,
            self::SIGNER_CANCELED,
            self::SIGNER_COMPLETED,
            self::SIGNER_SIGNED,
            self::SIGNER_EXPIRATION_DATE_UPDATED,
            self::SIGNER_SIGNATURE_REQUESTED
        ];
    }
}


