<?php
/**
 * EmailNotification
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public Api v3
 *
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EmailNotification Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmailNotification implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmailNotification';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'disabled' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'disabled' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'disabled' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'disabled' => 'disabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'disabled' => 'setDisabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'disabled' => 'getDisabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_NOT_SIGNED = 'signer.signature_request_canceled_due_to_an_error.signer_who_has_not_signed';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_ALREADY_SIGNED = 'signer.signature_request_canceled_due_to_an_error.signer_who_has_already_signed';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_NOT_SIGNED = 'signer.signature_request_canceled_by_sender.signer_who_has_not_signed';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_ALREADY_SIGNED = 'signer.signature_request_canceled_by_sender.signer_who_has_already_signed';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_ONE_SIGNER = 'signer.signature_request_done.signature_request_contains_one_signer';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_MULTIPLE_SIGNERS = 'signer.signature_request_done.signature_request_contains_multiple_signers';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_WITH_MULTIPLE_SIGNERS_SIGNED_SIGNED_BY_A_SIGNER = 'signer.signature_request_with_multiple_signers_signed.signed_by_a_signer';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_UPDATED_NEW_EXPIRATION_DATE = 'signer.signature_request_updated.new_expiration_date';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_UPDATED_BY_SENDER_NEW_SIGNER_DETAILS = 'signer.signature_request_updated_by_sender.new_signer_details';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_FIRST_NOTIFICATION = 'signer.signature_request_signature_requested.first_notification';
    public const DISABLED_SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_REMINDER_TO_SIGN = 'signer.signature_request_signature_requested.reminder_to_sign';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDisabledAllowableValues()
    {
        return [
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_NOT_SIGNED,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_DUE_TO_AN_ERROR_SIGNER_WHO_HAS_ALREADY_SIGNED,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_NOT_SIGNED,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_CANCELED_BY_SENDER_SIGNER_WHO_HAS_ALREADY_SIGNED,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_ONE_SIGNER,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_DONE_SIGNATURE_REQUEST_CONTAINS_MULTIPLE_SIGNERS,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_WITH_MULTIPLE_SIGNERS_SIGNED_SIGNED_BY_A_SIGNER,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_UPDATED_NEW_EXPIRATION_DATE,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_UPDATED_BY_SENDER_NEW_SIGNER_DETAILS,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_FIRST_NOTIFICATION,
            self::DISABLED_SIGNER_SIGNATURE_REQUEST_SIGNATURE_REQUESTED_REMINDER_TO_SIGN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('disabled', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['disabled'] === null) {
            $invalidProperties[] = "'disabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets disabled
     *
     * @return string[]
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param string[] $disabled List of disabled email notifications
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $allowedValues = $this->getDisabledAllowableValues();
        if (array_diff($disabled, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'disabled', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


