<?php
/**
 * DeprecatedApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public Api v3
 *
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DeprecatedApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeprecatedApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createIdDocumentVerification
     *
     * [DEPRECATED] Initiate a new ID document verification.
     *
     */
    public function testCreateIdDocumentVerification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankAccountVerifications
     *
     * [DEPRECATED] List Bank Account Verifications.
     *
     */
    public function testGetBankAccountVerifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBankAccountVerificationsBankAccountVerificationId
     *
     * [DEPRECATED] Retrieve a bank account verification.
     *
     */
    public function testGetBankAccountVerificationsBankAccountVerificationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIdDocumentVerification
     *
     * [DEPRECATED] Retrieve an ID document verification.
     *
     */
    public function testGetIdDocumentVerification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIdDocumentVerifications
     *
     * [DEPRECATED] List ID Document Verifications.
     *
     */
    public function testGetIdDocumentVerifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBankAccountVerifications
     *
     * [DEPRECATED] Initiate a new Bank Account Verification.
     *
     */
    public function testPostBankAccountVerifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postDocuments
     *
     * [DEPRECATED] Upload a Document.
     *
     */
    public function testPostDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
