<?php
/**
 * SignerConsentRequestApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public Api v3
 *
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SignerConsentRequestApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SignerConsentRequestApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestId
     *
     * Delete a Signer Consent Request.
     *
     */
    public function testDeleteSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestIdSignersSignerId
     *
     * Remove a Signer from a given Signer Consent Request.
     *
     */
    public function testDeleteSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestIdSignersSignerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSignatureRequestsSignatureRequestIdSignerConsentRequests
     *
     * List Signer Consent Requests of the Signature Request.
     *
     */
    public function testGetSignatureRequestsSignatureRequestIdSignerConsentRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestId
     *
     * Update a Signer Consent Request.
     *
     */
    public function testPatchSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSignatureRequestsSignatureRequestIdConsentRequests
     *
     * Add Signer Consent Request to a Signature Request.
     *
     */
    public function testPostSignatureRequestsSignatureRequestIdConsentRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestIdSignersSignerId
     *
     * Adds a Signer to a given Signer Consent Request.
     *
     */
    public function testPutSignatureRequestsSignatureRequestIdConsentRequestsConsentRequestIdSignersSignerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
