<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface ArchiveApiInterface {


    /**
     * Operation getArchivesArchivedFileIdDownload
     *
     * Download archived file
     * @param string $archivedFileId
     * @return \Illuminate\Http\UploadedFile | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\NotFoundResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     */
    public function getArchivesArchivedFileIdDownload(
            string $archivedFileId,
    ):
        \Illuminate\Http\UploadedFile | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\NotFoundResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation postArchives
     *
     * Direct upload an archived file
     * @param \Illuminate\Http\UploadedFile $file
     * @param null | string $workspaceId
     * @param null | string $archiveY
     * @param null | string[] $tags
     * @param null | string $expiredAt
     * @return \OpenAPI\Server\Model\ArchivedFile | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\NotFoundResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     */
    public function postArchives(
            \Illuminate\Http\UploadedFile $file,
            ?string $workspaceId,
            ?string $archiveY,
            ?array $tags,
            ?string $expiredAt,
    ):
        \OpenAPI\Server\Model\ArchivedFile | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\NotFoundResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;

}
