<?php declare(strict_types=1);

/**
 * Public Api v3
 * Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 3.0
 * Contact: contact@yousign.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface DeprecatedApiInterface {


    /**
     * Operation createIdDocumentVerification
     *
     * [DEPRECATED] Initiate a new ID document verification
     * @param null | string $firstName
     * @param null | string $lastName
     * @param null | \OpenAPI\Server\Model\LegacyCreateIdDocumentVerificationDocumentType $documentType
     * @param null | \Illuminate\Http\UploadedFile $file
     * @param null | \Illuminate\Http\UploadedFile $additionalFile
     * @return \OpenAPI\Server\Model\LegacyIdDocumentVerificationCreated | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function createIdDocumentVerification(
            ?string $firstName,
            ?string $lastName,
            ?\OpenAPI\Server\Model\LegacyCreateIdDocumentVerificationDocumentType $documentType,
            ?\Illuminate\Http\UploadedFile $file,
            ?\Illuminate\Http\UploadedFile $additionalFile,
    ):
        \OpenAPI\Server\Model\LegacyIdDocumentVerificationCreated | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation getBankAccountVerifications
     *
     * [DEPRECATED] List Bank Account Verifications
     * @param null | string $after
     * @param null | int $limit
     * @param null | \OpenAPI\Server\Model\GetBankAccountVerificationsStatusParameter $status
     * @return \OpenAPI\Server\Model\GetBankAccountVerifications200Response | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function getBankAccountVerifications(
            ?string $after,
            ?int $limit,
            ?\OpenAPI\Server\Model\GetBankAccountVerificationsStatusParameter $status,
    ):
        \OpenAPI\Server\Model\GetBankAccountVerifications200Response | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation getBankAccountVerificationsBankAccountVerificationId
     *
     * [DEPRECATED] Retrieve a bank account verification
     * @param string $bankAccountVerificationId
     * @return \OpenAPI\Server\Model\GetBankAccountVerificationsBankAccountVerificationId200Response | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\NotFoundResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function getBankAccountVerificationsBankAccountVerificationId(
            string $bankAccountVerificationId,
    ):
        \OpenAPI\Server\Model\GetBankAccountVerificationsBankAccountVerificationId200Response | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\NotFoundResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation getIdDocumentVerification
     *
     * [DEPRECATED] Retrieve an ID document verification
     * @param string $idDocumentVerificationId
     * @return \OpenAPI\Server\Model\GetIdDocumentVerification200Response | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\NotFoundResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function getIdDocumentVerification(
            string $idDocumentVerificationId,
    ):
        \OpenAPI\Server\Model\GetIdDocumentVerification200Response | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\NotFoundResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation getIdDocumentVerifications
     *
     * [DEPRECATED] List ID Document Verifications
     * @param null | string $after
     * @param null | int $limit
     * @param null | \OpenAPI\Server\Model\GetBankAccountVerificationsStatusParameter $status
     * @return \OpenAPI\Server\Model\GetIdDocumentVerifications200Response | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function getIdDocumentVerifications(
            ?string $after,
            ?int $limit,
            ?\OpenAPI\Server\Model\GetBankAccountVerificationsStatusParameter $status,
    ):
        \OpenAPI\Server\Model\GetIdDocumentVerifications200Response | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation postBankAccountVerifications
     *
     * [DEPRECATED] Initiate a new Bank Account Verification
     * @param \Illuminate\Http\UploadedFile $file
     * @param null | string $firstName
     * @param null | string $lastName
     * @param null | string $iban
     * @param null | string $bic
     * @param null | string $legalEntityName
     * @return \OpenAPI\Server\Model\LegacyBankAccountVerificationCreated | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function postBankAccountVerifications(
            \Illuminate\Http\UploadedFile $file,
            ?string $firstName,
            ?string $lastName,
            ?string $iban,
            ?string $bic,
            ?string $legalEntityName,
    ):
        \OpenAPI\Server\Model\LegacyBankAccountVerificationCreated | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;


    /**
     * Operation postDocuments
     *
     * [DEPRECATED] Upload a Document
     * @param \Illuminate\Http\UploadedFile $file
     * @param \OpenAPI\Server\Model\CreateDocumentFromMultipartNature $nature
     * @param null | string $insertAfterId
     * @param null | string $password
     * @param null | string $name
     * @param null | \OpenAPI\Server\Model\InitialsArea $initials
     * @param null | bool $parseAnchors
     * @return \OpenAPI\Server\Model\Document | \OpenAPI\Server\Model\BadRequestResponse | \OpenAPI\Server\Model\UnauthorizedResponse | \OpenAPI\Server\Model\ForbiddenResponse | \OpenAPI\Server\Model\MethodNotAllowed | \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | \OpenAPI\Server\Model\TooManyRequestsResponse | \OpenAPI\Server\Model\InternalServerError
     * @deprecated
     */
    public function postDocuments(
            \Illuminate\Http\UploadedFile $file,
            \OpenAPI\Server\Model\CreateDocumentFromMultipartNature $nature,
            ?string $insertAfterId,
            ?string $password,
            ?string $name,
            ?\OpenAPI\Server\Model\InitialsArea $initials,
            ?bool $parseAnchors,
    ):
        \OpenAPI\Server\Model\Document | 
        \OpenAPI\Server\Model\BadRequestResponse | 
        \OpenAPI\Server\Model\UnauthorizedResponse | 
        \OpenAPI\Server\Model\ForbiddenResponse | 
        \OpenAPI\Server\Model\MethodNotAllowed | 
        \OpenAPI\Server\Model\UnsupportedMediaTypeResponse | 
        \OpenAPI\Server\Model\TooManyRequestsResponse | 
        \OpenAPI\Server\Model\InternalServerError
    ;

}
